name: Test Daily Summary
on:
  workflow_dispatch:  # This allows manual triggering only

jobs:
  test-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Supabase Edge Function
      run: |
        echo "Testing connection to Supabase..."
        echo "Supabase URL: ${{ secrets.SUPABASE_URL }}"
        echo "Calling automated-daily-summary function..."
        
        response=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"test": true}' \
          "${{ secrets.SUPABASE_URL }}/functions/v1/automated-daily-summary")
        
        echo "Response: $response"
        
        # Extract HTTP status
        http_status=$(echo "$response" | grep "HTTP_STATUS:" | cut -d: -f2)
        
        if [ "$http_status" -eq 200 ]; then
          echo "✅ SUCCESS: Function called successfully!"
        else
          echo "❌ ERROR: HTTP Status $http_status"
          exit 1
        fi
